<a href="https://colab.research.google.com/github/adelladella/AVD_MiniProject/blob/main/CHECK_POINT_2_Adella_Putri_2409116006.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Checkpoint 2 - Data Understanding & Data Preparation**

**Nama** : Adella Putri

**NIM** : 2409116006

**Kelas** : A' Sitem Informasi 2024

**Tema Dataset** :Retail Sales Dataset

Unveiling Retail Trends: A Dive into Sales Patterns and Customer Profiles

**Sumber** : https://www.kaggle.com/datasets/mohammadtalib786/retail-sales-dataset

# **DATA UNDERSTANDING**

In [ ]:
import pandas as pd

## Membaca Data

In [ ]:
df = pd.read_csv("//content/drive/MyDrive/PRAKTIKUM AVD/retail_sales_dataset (1).csv")

df

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100
...,...,...,...,...,...,...,...,...,...
995,996,2023-05-16,CUST996,Male,62,Clothing,1,50,50
996,997,2023-11-17,CUST997,Male,52,Beauty,3,30,90
997,998,2023-10-29,CUST998,Female,23,Beauty,4,25,100
998,999,2023-12-05,CUST999,Female,36,Electronics,3,50,150
999,1000,2023-04-12,CUST1000,Male,47,Electronics,4,30,120

## Pemeriksaan Struktur Data

Menampilkan 5 baris pertama Data.

In [ ]:
df.head()

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100

Menampilkan 5 baris terakhir Data.

In [ ]:
df.tail()

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
995,996,2023-05-16,CUST996,Male,62,Clothing,1,50,50
996,997,2023-11-17,CUST997,Male,52,Beauty,3,30,90
997,998,2023-10-29,CUST998,Female,23,Beauty,4,25,100
998,999,2023-12-05,CUST999,Female,36,Electronics,3,50,150
999,1000,2023-04-12,CUST1000,Male,47,Electronics,4,30,120

Menampilkan Informasi terkait Data.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    1000 non-null   int64
 1   Date              1000 non-null   object
 2   Customer ID       1000 non-null   object
 3   Gender            1000 non-null   object
 4   Age               1000 non-null   int64
 5   Product Category  1000 non-null   object
 6   Quantity          1000 non-null   int64
 7   Price per Unit    1000 non-null   int64
 8   Total Amount      1000 non-null   int64
dtypes: int64(5), object(4)
memory usage: 70.4+ KB

Melihat dan menampilkan tipe data pada masing-masing kolom

In [ ]:
df.dtypes

Transaction ID       int64
Date                object
Customer ID         object
Gender              object
Age                  int64
Product Category    object
Quantity             int64
Price per Unit       int64
Total Amount         int64
dtype: object

Menampilkan jumlah baris dan kolom dalam data.

In [ ]:
print("Baris : ", df.shape[0])
print("Baris : ", df.shape[1])

Baris :  1000
Baris :  9

Memeriksa Statistik Deksriptif Dataset.

In [ ]:
df.describe()

       Transaction ID         Age     Quantity  Price per Unit  Total Amount
count     1000.000000  1000.00000  1000.000000     1000.000000   1000.000000
mean       500.500000    41.39200     2.514000      179.890000    456.000000
std        288.819436    13.68143     1.132734      189.681356    559.997632
min          1.000000    18.00000     1.000000       25.000000     25.000000
25%        250.750000    29.00000     1.000000       30.000000     60.000000
50%        500.500000    42.00000     3.000000       50.000000    135.000000
75%        750.250000    53.00000     4.000000      300.000000    900.000000
max       1000.000000    64.00000     4.000000      500.000000   2000.000000

Menganalisis hubungan antar variabel dalam data.

In [ ]:
df.select_dtypes(include=['number']).corr()

,Transaction ID,Age,Quantity,Price per Unit,Total Amount
Transaction ID,1.000000,0.065191,-0.026623,-0.060837,-0.075034
Age,0.065191,1.000000,-0.023737,-0.038423,-0.060568
Quantity,-0.026623,-0.023737,1.000000,0.017501,0.373707
Price per Unit,-0.060837,-0.038423,0.017501,1.000000,0.851925
Total Amount,-0.075034,-0.060568,0.373707,0.851925,1.000000

# **DATA PREPARATION**

Pemeriksaan data untuk mendeteksi nilai yang hilang.

In [ ]:
print((df.isna().sum() / len(df)) * 100)

Transaction ID      0.0
Date                0.0
Customer ID         0.0
Gender              0.0
Age                 0.0
Product Category    0.0
Quantity            0.0
Price per Unit      0.0
Total Amount        0.0
dtype: float64

Pemeriksaan adanya duplikasi dalam data.

In [ ]:
print(f"Jumlah data duplikat: {df.duplicated().sum()}")
print("Data yang tertera dalam dataset tidak memiliki duplikasi data antar baris.")

Jumlah data duplikat: 0
Data yang tertera dalam dataset tidak memiliki duplikasi data antar baris.

Pemeriksaan terhadap adanya Outliers pada data.

In [ ]:
results = []

cols = df.select_dtypes(include=['float64', 'int64']).columns

for col in cols:
    q1 = df[col].quantile(0.25)
    q3 = df[col].quantile(0.75)
    iqr = q3 - q1
    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr

    outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]
    percent_outliers = (len(outliers) / len(df)) * 100

    results.append({'Kolom': col, 'Persentase Outliers': percent_outliers})

print(results)
print(results)

[{'Kolom': 'Transaction ID', 'Persentase Outliers': 0.0}, {'Kolom': 'Age', 'Persentase Outliers': 0.0}, {'Kolom': 'Quantity', 'Persentase Outliers': 0.0}, {'Kolom': 'Price per Unit', 'Persentase Outliers': 0.0}, {'Kolom': 'Total Amount', 'Persentase Outliers': 0.0}, {'Kolom': 'Total_Revenue', 'Persentase Outliers': 0.0}]
[{'Kolom': 'Transaction ID', 'Persentase Outliers': 0.0}, {'Kolom': 'Age', 'Persentase Outliers': 0.0}, {'Kolom': 'Quantity', 'Persentase Outliers': 0.0}, {'Kolom': 'Price per Unit', 'Persentase Outliers': 0.0}, {'Kolom': 'Total Amount', 'Persentase Outliers': 0.0}, {'Kolom': 'Total_Revenue', 'Persentase Outliers': 0.0}]

Pemeriksaan pada Nilai yang tidak Konsisten(Inconsistent Values)

- Cek nilai unik dalam kolom kategori produk

In [ ]:
print("Kategori Produk:", df["Product Category"].unique())

Kategori Produk: ['Beauty' 'Clothing' 'Electronics']

- Cek nilai unik dalam kolom gender

In [ ]:
print("Gender:", df["Gender"].unique())

Gender: ['Male' 'Female']

- Cek nilai unik dalam kolom usia pelanggan

In [ ]:
print("Rentang Usia Pelanggan:", df["Age"].unique())

Rentang Usia Pelanggan: [34 26 50 37 30 45 46 63 52 23 35 22 64 42 19 27 47 62 18 49 28 38 43 39
 44 51 58 48 55 20 40 54 36 31 21 57 25 56 29 61 32 41 59 60 33 53 24]

- Cek nilai unik dalam kolom ID Pelanggan

In [ ]:
print("Customer ID (contoh 10 ID pertama):", df["Customer ID"].unique()[:10])

Customer ID (contoh 10 ID pertama): ['CUST001' 'CUST002' 'CUST003' 'CUST004' 'CUST005' 'CUST006' 'CUST007'
 'CUST008' 'CUST009' 'CUST010']

### Dataset ini tidak memerlukan penanganan lebih lanjut karena tidak terdapat nilai yang hilang, duplikat, outlier, atau nilai yang tidak konsisten

# **Construct Data**

Menambahkan Kolom Baru (Konstruksi Data)

In [ ]:
df['Revenue per Item'] = df['Total Amount'] / df['Quantity']
print("\n Revenue per Item ditambahkan:")
print(df[['Total Amount', 'Quantity', 'Revenue per Item']].head())

 Revenue per Item ditambahkan:
   Total Amount  Quantity  Revenue per Item
0           150         3              50.0
1          1000         2             500.0
2            30         1              30.0
3           500         1             500.0
4           100         2              50.0

Menambahkan Kolom Customer AGe Group

In [ ]:
def categorize_age(age):
    if age < 18:
        return "Teen"
    elif 18 <= age < 35:
        return "Young Adult"
    elif 35 <= age < 50:
        return "Middle-aged"
    else:
        return "Senior"

df['Customer Age Group'] = df['Age'].apply(categorize_age)
print("\n Customer Age Group ditambahkan:")
print(df[['Age', 'Customer Age Group']].head())

 Customer Age Group ditambahkan:
   Age Customer Age Group
0   34        Young Adult
1   26        Young Adult
2   50             Senior
3   37        Middle-aged
4   30        Young Adult

Menambah kategori belanja berdasarkan Total Amount

In [ ]:
q1 = df['Total Amount'].quantile(0.33)
q2 = df['Total Amount'].quantile(0.66)

def categorize_spending(value):
    if value <= q1:
        return "Low Spender"
    elif value <= q2:
        return "Medium Spender"
    else:
        return "High Spender"

df['Spending Category'] = df['Total Amount'].apply(categorize_spending)
print("\n✅ Spending Category ditambahkan:")
print(df[['Total Amount', 'Spending Category']].head())

✅ Spending Category ditambahkan:
   Total Amount Spending Category
0           150    Medium Spender
1          1000      High Spender
2            30       Low Spender
3           500    Medium Spender
4           100    Medium Spender

In [ ]:
print(df.head())

   Transaction ID        Date Customer ID  Gender  Age Product Category  \
0               1  2023-11-24     CUST001    Male   34           Beauty
1               2  2023-02-27     CUST002  Female   26         Clothing
2               3  2023-01-13     CUST003    Male   50      Electronics
3               4  2023-05-21     CUST004    Male   37         Clothing
4               5  2023-05-06     CUST005    Male   30           Beauty

   Quantity  Price per Unit  Total Amount  Total_Revenue  Revenue per Item  \
0         3              50           150            150              50.0
1         2             500          1000           1000             500.0
2         1              30            30             30              30.0
3         1             500           500            500             500.0
4         2              50           100            100              50.0

  Customer Age Group Spending Category
0        Young Adult    Medium Spender
1        Young Adult      High Spender
2             Senior       Low Spender
3        Middle-aged    Medium Spender
4        Young Adult    Medium Spender

Reduksi Data dengan hanya memilih kolom yang paling penting

In [ ]:
df_reduced = df[['Transaction ID', 'Date', 'Customer ID', 'Age', 'Customer Age Group',
                 'Gender', 'Product Category', 'Quantity', 'Price per Unit',
                 'Total Amount', 'Revenue per Item', 'Spending Category']]

print(df_reduced.head())

   Transaction ID        Date Customer ID  Age Customer Age Group  Gender  \
0               1  2023-11-24     CUST001   34        Young Adult    Male
1               2  2023-02-27     CUST002   26        Young Adult  Female
2               3  2023-01-13     CUST003   50             Senior    Male
3               4  2023-05-21     CUST004   37        Middle-aged    Male
4               5  2023-05-06     CUST005   30        Young Adult    Male

  Product Category  Quantity  Price per Unit  Total Amount  Revenue per Item  \
0           Beauty         3              50           150              50.0
1         Clothing         2             500          1000             500.0
2      Electronics         1              30            30              30.0
3         Clothing         1             500           500             500.0
4           Beauty         2              50           100              50.0

  Spending Category
0    Medium Spender
1      High Spender
2       Low Spender
3    Medium Spender
4    Medium Spender

# **KESIMPULAN**

Dataset ini terdiri dari 1000 baris dan 9 kolom yang mencakup informasi transaksi pelanggan.
Setelah dilakukan pemeriksaan, ditemukan bahwa:

- Tidak ada nilai yang hilang (missing values).
- Tidak ada data duplikat.
- Tidak ditemukan outliers signifikan dalam data numerik (Age, Quantity, Price per Unit, Total Amount).
- Data kategori (Gender, Product Category) telah dicek dan tidak mengandung nilai yang tidak konsisten.

Dataset telah diperiksa secara menyeluruh.
- Tidak ada nilai yang hilang, duplikat, maupun outliers signifikan.
- Seluruh nilai kategori telah dikonfirmasi konsisten.

Pemeriksaan tambahan dilakukan pada:

- Customer ID = Memastikan setiap pelanggan memiliki ID unik.
- Age & Spending Patterns = Untuk memahami distribusi usia dan kebiasaan belanja pelanggan.

Untuk meningkatkan wawasan dari dataset, beberapa kolom tambahan dibuat:
- Revenue per Item → Pendapatan per item dihitung sebagai Total Amount / Quantity.
- Customer Age Group → Klasifikasi umur pelanggan ke dalam empat kategori:

< 18: Teen

18 - 34: Young Adult

35 - 49: Middle-aged

≥ 50: Senior
- Spending Category → Klasifikasi pelanggan berdasarkan total pembelanjaan:
- Low Spender (≤ 33% kuantil)
- Medium Spender (33%-66% kuantil)
- High Spender (> 66% kuantil)

Penambahan kolom ini membantu memahami pola belanja berdasarkan kelompok usia dan kategori pelanggan.

membuat dataset lebih ringkas dan relevan, hanya dipilih kolom-kolom paling penting, yaitu:
✅ Transaction ID, Date, Customer ID → Untuk analisis pelanggan & waktu transaksi.
✅ Age, Customer Age Group, Gender → Untuk analisis demografi pelanggan.
✅ Product Category, Quantity, Price per Unit, Total Amount → Untuk melihat pola pembelian.
✅ Revenue per Item, Spending Category → Untuk analisis perilaku belanja.

Dataset hasil reduksi tetap mencakup informasi esensial tanpa menghilangkan aspek penting dari analisis.

Untuk membuat dataset lebih ringkas dan relevan, hanya dipilih kolom-kolom paling penting, yaitu:
- Transaction ID, Date, Customer ID → Untuk analisis pelanggan & waktu transaksi.
- Age, Customer Age Group, Gender → Untuk analisis demografi pelanggan.
- Product Category, Quantity, Price per Unit, Total Amount → Untuk melihat pola pembelian.
- Revenue per Item, Spending Category → Untuk analisis perilaku belanja.

Dataset hasil reduksi tetap mencakup informasi esensial tanpa menghilangkan aspek penting dari analisis.

Reduksi data dilakukan agar dataset lebih ringkas dan mudah dianalisis tanpa menghilangkan informasi penting. Kolom yang kurang relevan dihapus, sementara kolom utama tetap dipertahankan untuk memahami pola belanja pelanggan dan demografi mereka.
Jadi, meskipun datanya lebih sedikit, diharapkan analisis tetap akurat dan fokus.